### ISSUE TITLE
[server-wallet(ish)] Onchain Service Discussion

### ISSUE THREAD

**Issue by LayneHaber** [statechannels/statechannels#2534] opened 2020-09-03 02:35 UTC
There are still several items to discuss regarding the behavior of the `OnchainService`. Here are a few (listed in no particular order):

- What is the best way to make this usable in a multichain environment? Multiple instances of the class? Configuring the service to handle multiple chains and providers?
- What's the best chain service <--> wallet <--> app architecture and division of responsibilities?
- How should the onchain service handle different types of asset holders? (think `ZKSyncDaiAssetHolder` or something)
- How should we handle historical event syncing?

This is by no means a comprehensive list, but it is a start!

**Comment by snario** [comment] 2020-09-03 13:49
I like the idea that it is the responsibility of a service external to the `server-wallet` to **set** definitively the on-chain funding state of the system. This has nice properties like externalizing the entirety of event interpretation, handling of orphaned blocks, handling confirmation windows, and other kinds of things like that to a separate service.

**Comment by LayneHaber** [comment] 2020-09-04 03:23
I agree, I think the part I'm hung up on is the best way to get that information to the wallet (I'm assuming that the chain store and the channel store are completely separate). We can allow an accessor method on the service interface, but another idea @andrewgordstewart and I threw around a bit was to have the service emit essentially the same event twice, once when its emitted by the contract, and once when it is finalized. The "app" (which I consider to be the thing governing the wallet, and already responsible for routing messages to the wallet), can then register a handler to the events, and push that information via some `pushEvent`, `setAdjudicatorState`, etc. method on the wallet.

I think I'm lacking some context into what the wallet will need to get from the chain and when that may be messing with my mental models slightly on this front, so this may not be the most ideal way for the data to flow

**Comment by snario** [comment] 2020-09-04 12:18
The wallet needs to know:

- When its user has made a deposit
- When a counterparty has made a deposit
- When a withdrawal has been made
- When a challenge has been initiated
- When a challenge has been responded to
- When a checkpoint has been made

Specifically it needs to know when it can be 100% confident in this information in order to make a decision based on it. For example, it may be waiting to sign a state until after it observes some funds deposited on-chain. Or, it may not sign any new states until it sees a challenge responded to on-chain. Or, if it initiates a challenge, it may lock that channel preventing any future states being signed for it until that challenge has been responded to (i.e., because otherwise it is committing an attributable fault).

Okay so that means there _needs_ to be some functionality which (a) **sets** the funding state of a channel and (b) **sets** the adjudication state of a channel. I highlight the word "set" because this is an authoritative statement made by some piece of software; perhaps the wallet, perhaps the "on chain service".

### Which software is responsible for (a) and (b)?
What factors contribute to this decision? Well, let's list the kinds of things this software must deal with:

- Query the current state of a blockchain
- Monitor an underlying blockchain for state changes (i.e., events like `Deposited`, `TransferredAssets`, etc...)
- React to orphaned blocks in deciding how confident it is in its understanding of the state of the chain
- Synchronize historical blockchain data between some block number to the present, and identify what changes have happened that warrant a new authoritative statement on the current state of funding or adjudication [1]

You can separate this into two buckets:

1. Retrieve information from external APIs to learn about blockchain state
2. Reconcile what it receives and deem something to be the "confirmed" current state

There is a strong argument that the wallet should be the piece of software which does (2) and the on chain service solely be responsible for (1), since the wallet is _already designed_ to be a deterministic "decision maker" that is robust and crash tolerant. 

However, there is an important caveat that I've been considering recently. Funding and adjudication of channels are _related_ but not necessarily coupled. For example, funding can occur on the ethereum blockchain (i.e., `ETHAssetHolder`) alongside challenging (i.e., `NitroAdjudicator`), but you might also want to fund a ledger / direct channel based on another approach like a transaction on a [zkSync](https://zksync.io/) roll up.

In the roll up case, you are not monitoring Infura, you are monitoring the API exposed by an operator to determine whether a deposit happened. For this situation you might not be thinking about orphaned blocks, for example. So there is a question: should the wallet be responsible for interpreting the result of a zkSync API response?

Another way of thinking about this problem is that an `AssetHolder` may not necessarily emit a `Deposited` and `AssetTransferred` event in every situation. For on-chain assets like ETH or an ERC20 token, certainly we will see these events. However if the asset is something which has instant finality / redeem-ability that the user believes has value, then these events would only get emitted on-chain in the event of the execution of that finality / redemption. There are many assets like this in ethereum today:

- xDai
- zkSync Assets
- Meta-transactions
- Probabilistic Nanopayments
- Merkle airdrops

This seems like an area where we can make a design decision to support extensions that can implement this sort of thing in the future and keep the implementation details outside of the `server-wallet`. All that we require is that the "app" connect some piece of software that can make decisions (i.e., (a) and (b)) about funding state. [2]

Finally, since we intend on auditing the server wallet in the near future, this becomes an area of potentially added complexity that, were it to be decoupled, could dramatically simplify the invariants we expect the server wallet to hold true.

I think the below table summarizes my position:

| Software        | Monitor Chain                                                                          | Interpret Events                                                                                                                                                                                |
|-----------------|----------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Wallet          | - Requires connection to internet - Adds complexity to database schema                 | + Naturally fits into computation model of the wallet (i.e., decision tree based on data) - Decreases auditability of the wallet (i.e., increases scope)                                        |
| Onchain-Service | + Separation of concerns + One process can service several horizontally scaled wallets | - Adds complexity to on-chains service (e.g., understand orphaned blocks, parse events) + Creates cleaner interface to be implemented for supporting Layer 2 services (e.g., zkSync, xDai, etc) |

### Notes

- [1]: It _is_ possible that you restart this service and find that you were challenged, you did not respond, and thus the state has been finalized at something you did not expect. This software should probably handle this and set the state of the wallet to the finalized on-chain state, to allow the wallet to reconfigure itself to accept this failure.

- [2]: Note also that I only said _funding_ state there; perhaps there is a generic piece of software that the wallet handles for _adjudication events_ (since they should all happen on ethereum... probably?) but the funding part is extensible.

**Comment by snario** [comment] 2020-09-04 12:27
Based on the above I would propose an API like:

**Wallet -> Chain**
- `fundChannel(channelId: Bytes32, amount: BN, assetHolderAddress: Address)`
- `withdrawFunds(finalState: SignedState)`
- `challengeChannel(channelId: Bytes32, support: SignedState[])`
- `checkpointChannel(channelId: Bytes32, support: SignedState[])`
- `respondToChallenge(channelId: Bytes32, response: SignedState)`

**Chain -> Wallet**
- `setFunding(channelId: Bytes32, amount: BN)`
- `setChallengeState(channelId: Bytes32, state: SignedState)`

**Comment by snario** [comment] 2020-09-10 16:15
Instead, `setFunding` should be `fundingChanged(channelId: Bytes32, newAmount: BN, assetHolderAddress: Address)`. Include the asset holder address because a channel may have multiple asset holder addresses in its outcome.

**Comment by snario** [comment] 2020-09-10 16:17
`fundingChanged` should perhaps also have a `depth`

**Closed** 2021-01-23 03:50 UTC
Labels: connext, discussion, server-wallet
