### ISSUE TITLE
An objective can spawn another objective

### ISSUE THREAD

**Issue by kerzhner** [statechannels/statechannels#3239] opened 2021-02-02 00:15 UTC
Consider closing and defunding a channel.
- The `CloseChannel` objective is designed to exchange closing states between participants regardless of funding.
- The `DefundChannel` objective defunds a channel and contains funding specific logic.

For closing a payment channel, a potential sequence of events is:
- `CloseChannel` objective is created as a consequence of the application request to close a ledger channel.
- `CloseChannel` objective creates a new `DefundChannel` objective.

At the moment, [`crankUntilIdle`](https://github.com/statechannels/statechannels/blob/master/packages/server-wallet/src/wallet/wallet.ts#L717):
1. Pulls out a list of approved objectives.
1. Iterates through the list and cranks each individual objective.

The result is that, if an objective creates a new objective, the new objective will not be processed until `crankUntilIdle` is called again. This might not happen until a new API call to the wallet.

**Comment by andrewgordstewart** [comment] 2021-02-02 00:25
I think this is a duplicate of #3227 

Also, is
> The CloseChannel objective is designed to exchange closing states between participants regardless of funding.

an accurate description of the wallet's current behaviour? I thought it was _also_ responsible for defunding the channel by submitting a `concludeTransferAndWithdrawAll` transaction (or whatever it's called)

**Comment by kerzhner** [comment] 2021-02-02 01:17
Good call. We can close this issue.

The description of the `CloseChannelObjective` is (my understanding of) how we would like the objective to behave, not how it currently behaves.

**Closed** 2021-02-02 01:18 UTC
